version: '3'

services:
  acq_qs:
    image: queueserver:latest
    volumes:
      - ${BEAMLINE_PODS_DIR}/config/ipython:/usr/local/share/ipython
      - ${NBS_PODS_DIR}/config/tiled/profiles:/etc/tiled/profiles
      - ${NBS_PODS_DIR}/config/bluesky:/etc/bluesky
      - ${NBSDIR}:/usr/local/src/xraygui
    command: >
      bash -c "
        tail -f /dev/null &&
        pixi run qs-dev
      "
