version: '3'
networks:
  bluesky-services_bluesky:
    external: true
services:
  nbs-viewer:
    image: ghcr.io/xraygui/nbs-pods/viewer:latest
    volumes:
      - /run/user/${UID}:/run/user/${UID}
    devices:
      - /dev/dri:/dev/dri
      - /dev/video0:/dev/video0
    environment:
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - QT_QPA_PLATFORM=wayland
      - IPYTHONDIR=/usr/local/share/ipython
      - XDG_RUNTIME_DIR=/run/user/${UID}
    command: pixi run viewer
    networks:
      - bluesky-services_bluesky
