version: '3'

networks:
  bluesky-services_bluesky:
    external: true

services:
  acq_qs:
    image: ghcr.io/xraygui/nbs-pods/queueserver:latest
    environment:
      - IPYTHONDIR=/usr/local/share/ipython
      - EPICS_CA_AUTO_ADDR_LIST=yes
    command: pixi run qs
    networks:
      - bluesky-services_bluesky
